name: CI

on:
  push:
    branches:
      - master

jobs:
  security-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install Dependencies
        run: |
          composer install

      - name: Install local-php-security-checker
        run: composer global require sensiolabs/security-checker

      - name: SecurityChecker
        run: php ~/.composer/vendor/bin/local-php-security-checker composer.lock

  php-code-standard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install Dependencies
        run: |
          composer install

      - name: Install php-cs-fixer
        run: |
          wget https://cs.symfony.com/download/php-cs-fixer-v3.phar -O php-cs-fixer
          chmod +x php-cs-fixer
          sudo mv php-cs-fixer /usr/local/bin/php-cs-fixer

      - name: Install PHPStan
        run: composer global require phpstan/phpstan

      - name: Add PHPStan to PATH
        run: echo "::add-path::~/.composer/vendor/bin"

      - name: PHP Coding Standards
        run: |
          php-cs-fixer fix ./src --dry-run --rules=@Symfony --verbose
          phpstan analyse ./src -l3
          phpdd ./src
          phpcpd ./src --exclude './src/Controller/Admin/' --exclude './src/Entity'

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install Dependencies
        run: |
          composer install

      - name: Install php-cs-fixer
        run: |
          wget https://cs.symfony.com/download/php-cs-fixer-v3.phar -O php-cs-fixer
          chmod +x php-cs-fixer
          sudo mv php-cs-fixer /usr/local/bin/php-cs-fixer

      - name: Install PHPStan
        run: composer global require phpstan/phpstan

      - name: Add PHPStan to PATH
        run: echo "::add-path::~/.composer/vendor/bin"

      - name: PHP Lint
        run: |
          ./bin/console lint:twig templates --env=prod
          ./bin/console lint:yaml config --parse-tags
          ./bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction
