name: CI

on:
  push:
    branches:
      - master

jobs:
  security-checker:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install Dependencies
        run: composer install

      - name: SecurityChecker
        run: local-php-security-checker composer.lock

  php-code-standard:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install Dependencies
        run: composer install

      - name: PHP Coding Standards
        run: |
          php-cs-fixer fix ./src --dry-run --rules=@Symfony --verbose
          phpstan analyse ./src -l3
          phpdd ./src
          phpcpd ./src --exclude './src/Controller/Admin/' --exclude './src/Entity'

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install Dependencies
        run: composer install

      - name: PHP Lint
        run: |
          ./bin/console lint:twig templates --env=prod
          ./bin/console lint:yaml config --parse-tags
          ./bin/console doctrine:schema:validate --skip-sync -vvv --no-interaction